#ifndef RTW_HEADER_modPSK_mod2_acc_types_h_
#define RTW_HEADER_modPSK_mod2_acc_types_h_
typedef struct P_SampleandHold_modPSK_mod2_T_ P_SampleandHold_modPSK_mod2_T ;
typedef struct P_NEGATIVEEdge_modPSK_mod2_T_ P_NEGATIVEEdge_modPSK_mod2_T ;
typedef struct P_POSITIVEEdge_modPSK_mod2_T_ P_POSITIVEEdge_modPSK_mod2_T ;
typedef struct P_modPSK_mod2_T_ P_modPSK_mod2_T ;
#endif
